---
output:
  github_document:
    html_preview: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r knitrsetup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
options(tibble.print_min = 5, tibble.print_max = 5)
library(drake)
library(ggplot2)
theme_set(theme_bw())
library(dplyr)
```

# HYSTERESIS
Tracking moisture in soil cores

Run: `r Sys.Date()`

```{r, echo=FALSE, message=FALSE}
gc()
source("1-moisture_tracking.R")

# readd("massdata") %>% 

mass %>% group_by(Core) %>% 
  dplyr::mutate(Hours = as.integer(difftime(Stop_datetime, min(Stop_datetime), units = "hours"))) ->
  massdata

ggplot(massdata, aes(Stop_datetime, Moisture_perc)) +
  geom_point() + geom_line()+
  facet_wrap(~Core_assignment)+
  ylim(0,175)

massdata %>% 
  group_by(Core) %>% 
  mutate(moisture = if_else(Stop_datetime == max(Stop_datetime),Moisture_perc,as.numeric(NA))) %>% 
  dplyr::filter(!is.na(moisture)) %>% 
  ungroup %>% 
  group_by(Core_assignment) %>% 
  dplyr::summarize(moisture = round(mean(moisture),2))->current_moisture

print("Current moisture conditions")
knitr::kable(current_moisture)

 ```

