---
title: "7-nmr_markdown"
author: "Kaizad Patel"  
date: "4/7/2020"  
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>", 
                      fig.path = "images/7b-nmr_markdown/"
                      )

source("0-hysteresis_packages.R")
source("7a-nmr_spectra_setup.R")
source("6b-nmr_peaks_relabund.R")
```

## SPECTRA 
SCL = sandy clay loam (soil)  
SL = sandy loam (soil + sand)  


```{r}
spectra = read.csv("data/processed/nmr_spectra.csv.gz")

spectra_plot = 
  spectra %>% 
  dplyr::mutate(Core = as.character(Core))  %>% 
  na.omit()
```

```{r nmr_spectra_fm, fig.width=15, fig.height=5}
gg_nmr+
  geom_path(data=spectra[spectra$treatment=="FM",], aes(x = ppm, y = intensity, color = as.character(Core)),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(.~texture)+theme(legend.position = "none")+
  ggtitle("field moist")
```



```{r nmr_spectra, fig.width=15, fig.height=10}

gg_nmr+
  geom_path(data=spectra_plot[spectra_plot$sat_level=="100",], aes(x = ppm, y = intensity, color = Core),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(treatment~texture)+theme(legend.position = "none")+
  ggtitle("100 % saturation")

gg_nmr+
  geom_path(data=spectra_plot[spectra_plot$sat_level=="75",], aes(x = ppm, y = intensity, color = Core),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(treatment~texture)+theme(legend.position = "none")+
  ggtitle("75 % saturation")

gg_nmr+
  geom_path(data=spectra_plot[spectra_plot$sat_level=="50",], aes(x = ppm, y = intensity, color = Core),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(treatment~texture)+theme(legend.position = "none")+
  ggtitle("50 % saturation")

gg_nmr+
  geom_path(data=spectra_plot[spectra_plot$sat_level=="35",], aes(x = ppm, y = intensity, color = Core),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(treatment~texture)+theme(legend.position = "none")+
  ggtitle("35 % saturation")

gg_nmr+
  geom_path(data=spectra_plot[spectra_plot$sat_level=="5",], 
            aes(x = ppm, y = intensity, color = Core),
            alpha = 0.5)+
  ylim(-0.3,7)+
  facet_grid(treatment~texture)+theme(legend.position = "none")+
  ggtitle("5 % saturation")


```

representative spectra -- 50 % saturation

```{r nmr_spectra2, fig.width=8, fig.height=5}
subset_spectra = 
  spectra_plot %>% 
  filter(Core %in% c(120,115))
  
gg_nmr+
  geom_path(data=subset_spectra[subset_spectra$treatment=="Drying",], 
            aes(x = ppm, y = intensity))+
    geom_path(data=subset_spectra[subset_spectra$treatment=="Wetting",], 
            aes(x = ppm, y = intensity+1))+
  annotate("text", label = "rewetting", x = 9, y = 1.1)+
  annotate("text", label = "drying", x = 9, y = 0.1)+
  ylim(-0.1,3.5)+
  ylab("")+
  ggtitle("50% saturation")+
  
  theme(legend.position = "none",
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank()
)

```



## PEAKS
relative abundance for each sample
```{r peaks, fig.width=30, fig.height=30}
ggplot(data=rel_abund[rel_abund$soil_type=="Soil"&!rel_abund$treatment=="FM",], aes(x="", y=relabund, fill=group)) +
  geom_bar(stat="identity", alpha=0.7) +
  #geom_text(aes(x= "", y=pos, label = relabund), size=4) +  # note y = pos
  #facet_wrap(facets = .~source, labeller = label_value) +
  facet_wrap(sat_level+treatment~Core)+
  coord_polar(theta = "y")+
  theme_bw()+
  ggtitle("SCL")


ggplot(data=rel_abund[rel_abund$soil_type=="Soil_sand"&!rel_abund$treatment=="FM",], aes(x="", y=relabund, fill=group)) +
  geom_bar(stat="identity", alpha=0.7) +
  #geom_text(aes(x= "", y=pos, label = relabund), size=4) +  # note y = pos
  #facet_wrap(facets = .~source, labeller = label_value) +
  facet_wrap(sat_level+treatment~Core)+
  coord_polar(theta = "y")+
  theme_bw()+
  ggtitle("SL")

```



## PCA
```{r nmr_pca}
rel_abund = read.csv("data/processed/nmr_rel_abund_cores.csv")


relabund_pca=
  rel_abund %>% 
  ungroup %>% 
  dplyr::select(Core, treatment, sat_level, texture, group, relabund) %>% 
  spread(group, relabund) %>% 
  replace(.,is.na(.),0)  %>% 
  dplyr::mutate(sat_level = if_else(treatment=="FM","FM", as.character(sat_level))) %>% 
  dplyr::select(-1)

### scl
relabund_pca_scl_num = 
  relabund_pca %>% 
  filter(texture=="SCL") %>% 
  dplyr::select(.,-(1:3))

relabund_pca_scl_grp = 
  relabund_pca %>% 
  filter(texture=="SCL") %>% 
  dplyr::select(.,(1:3)) %>% 
  dplyr::mutate(row = row_number())

pca_scl = prcomp(relabund_pca_scl_num, scale. = T)
summary(pca_scl)

ggbiplot(pca_scl, obs.scale = 1, var.scale = 1, 
         groups = relabund_pca_scl_grp$treatment, ellipse = TRUE, circle = F,
         var.axes = TRUE)+
  geom_point(size=2,stroke=2, aes(color = groups, shape = as.factor(relabund_pca_scl_grp$sat_level)))+
  ggtitle("SCL texture")

### sl
relabund_pca_sl_num = 
  relabund_pca %>% 
  filter(texture=="SL") %>% 
  dplyr::select(.,-(1:3))

relabund_pca_sl_grp = 
  relabund_pca %>% 
  filter(texture=="SL") %>% 
  dplyr::select(.,(1:3)) %>% 
  dplyr::mutate(row = row_number())

pca_sl = prcomp(relabund_pca_sl_num, scale. = T)
summary(pca_sl)

ggbiplot(pca_sl, obs.scale = 1, var.scale = 1, 
         groups = relabund_pca_sl_grp$treatment, ellipse = TRUE, circle = F,
         var.axes = TRUE)+
  geom_point(size=2,stroke=2, aes(color = groups, shape = as.factor(relabund_pca_sl_grp$sat_level)))+
  ggtitle("SL texture")

```


## RELATIVE ABUNDANCE
```{r}
rel_abund = read.csv("data/processed/nmr_rel_abund.csv")
```

peaks in field moist soils

```{r}
rel_abund %>% 
  filter(treatment == "FM") %>% 
  dplyr::select(group, texture, relative_abundance) %>% 
  spread(texture, relative_abundance) %>% 
  knitr::kable(align = "r")
```

peaks in treatments

```{r}
rel_abund %>% 
  filter(!treatment == "FM") %>% 
  dplyr::mutate(sat_level = factor(sat_level, levels = c(5,35,50,75,100)),
                var = paste0(sat_level,"-",treatment)) %>% 
  dplyr::select(texture, group, var, relative_abundance) %>% 
   
  spread(var, relative_abundance) %>% 
  knitr::kable(align = "r")
```


## rel abund 

```{r}
rel_abund_cores = read.csv("data/processed/nmr_rel_abund_cores.csv")
arom = 
  rel_abund_cores %>% 
  filter(group %in% c("aromatic", "aliphatic1", "aliphatic2")) %>% 
  dplyr::select(Core, group, treatment, sat_level, texture, relabund) %>% 
  spread(group, relabund) %>% 
  dplyr::mutate(arom_aliph = aromatic/(aliphatic1+aliphatic2))


ggplot(arom, aes(x = sat_level, y = arom_aliph, color = treatment))+
  geom_point()+
  geom_smooth()+
  ylab("aromatic/aliphatic")+
  facet_grid(.~texture)+
  theme_kp()

ggplot(arom, aes(x = sat_level, y = aromatic, color = treatment))+
  geom_point()+
  geom_smooth()+
  ylab("aromatic")+
  facet_grid(.~texture)+
  theme_kp()
  
```


### rel abund waffle plots

```{r}
library(ggplot2)
library(dplyr)
library(schrute)
library(waffle)
#library(ggtext)
library(cowplot)
library(patchwork)
library(soilpalettes)

rel_abund = read.csv("data/processed/nmr_rel_abund.csv")

rel_abund_50_scl = 
  rel_abund %>% 
  filter(sat_level==50,
         texture=="SCL") %>% 
  ggplot()+
  geom_waffle(aes(fill=group,values=rel_abund),n_rows = 5,size=1.5,color="white", flip = F) + 
  coord_equal() +
scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+
  scale_fill_manual(values = soil_palette("podzol",4))+
  #guides(color=F) +
  facet_grid(treatment~.)+
  theme_classic()+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank())
  
ggdraw(rel_abund_50_scl)
```

